---
kind: ContainerVersion
apiVersion: custom.k8s.io/v1
metadata:
  name: myappcv
spec:
  imageRepo: <AWS_ACC_ID>.dkr.ecr.us-east-1.amazonaws.com/nearmap/cvm-example
  tag: demo-env
  pollIntervalSeconds: 30
  selector:
    cvapp: myapp
  container:
    name: myapp-container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
    cvapp: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: <AWS_ACC_ID>.dkr.ecr.us-east-1.amazonaws.com/nearmap/cvm-example:89e1602d1650aa1dfaa1ab3a971af19ba6081e57
        name: myapp-container
        ports:
        - containerPort: 80
        env:
        - name: STATS_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
  selector:
    app: myapp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  rules:
  - host: demo.nearmapdev.com
    http:
      paths:
      - path: /
        backend:
          serviceName: myapp
          servicePort: 80
