version: 2

defaults: &defaults
  docker:
    - image: nearmap/docker-ce
  working_directory: ~/go/src/github.com/nearmap/cvm-example

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container image
          command: |
            `aws ecr get-login --no-include-email --region us-east-1`
            docker build -t nearmap/cvm-example .

  push-to-container-registry:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: Push application docker image
          command: |
            `aws ecr get-login --no-include-email --region us-east-1`
            docker build -t nearmap/cvm-example .
            echo "Tagging container image with sha: ${CIRCLE_SHA1}"
            docker tag nearmap/cvm-example ${ECR_ENDPOINT}/nearmap/cvm-example:${CIRCLE_SHA1}
            docker push ${ECR_ENDPOINT}/nearmap/cvm-example:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - push-to-container-registry:
          requires:
            - build